---

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive the compressed artifact file
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Installing node dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i

- name: "Run node app with pm2"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node
  environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

- name: "Print message"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu